CREATE TABLE DEPT_tmp as SELECT * FROM DEPT d;

SELECT *
FROM DEPT_TMP;

-- update ~ set
UPDATE DEPT_TMP
SET loc = 'SEOUL';  -- 해당열 전체 수정

UPDATE DEPT_TMP
SET DNAME = 'DATABASE', LOC = 'BUSAN'
WHERE DEPTNO = 40;          -- 일부 부분만 수정할 때는 where 조건문 사용
-- 서브쿼리를 사용한 데이터 수정
UPDATE DEPT_TMP
SET (DNAME, LOC) = (SELECT DNAME, LOC FROM DEPT WHERE DEPTNO = 40)
WHERE DEPTNO = 40;
/* 삭제하기 */
CREATE TABLE EMP_TMP AS
SELECT *
FROM EMP;

DELETE
FROM EMP_TMP
WHERE JOB = 'SALESMAN';
-- 서브쿼리를 통한 삭제
DELETE
FROM EMP_TMP;       -- DATA만 삭제되고 TABLE은 삭제안됨

DROP TABLE EMP_TMP; -- TABLE 삭제(DROP 사용)
/* 트랜잭션 */
CREATE TABLE DEPT_TCL
AS SELECT *
FROM DEPT d;

INSERT INTO DEPT_TCL
VALUES (50, 'DATABASE', 'BUSAN');


UPDATE DEPT_TCL
SET LOC = 'BUSAN'
WHERE DEPTNO = 40;        -- 데이터 추가


DELETE
FROM DEPT_TCL
WHERE DNAME = 'RESEARCH'; -- 데이터 삭제

ROLLBACK;       -- 되돌리기

COMMIT;     -- 트랜잭선 반영

SELECT *
FROM DEPT_TCL;

/* VIEW */
CREATE VIEW VM_EMP AS
(SELECT EMPNO, ENAME, JOB, DEPTNO
FROM EMP e
WHERE DEPTNO = 20);

SELECT *
FROM VM_EMP;

SELECT *
FROM USER_VIEWS;

DROP VIEW VM_EMP;

-- 테이블, 데이터사전, 인덱스, 뷰, 시퀀스, 동의어 -> 오라클에서 객체

/* 데이터 사전 */
SELECT *
FROM DICT;  -- 사용가능한 데이터 사전

SELECT TABLE_NAME
FROM USER_TABLES;       -- 현재 접속자(ADAM)이 가지고 있는 테이블 조회

SELECT OWNER, TABLE_NAME
FROM ALL_TABLES;        -- 현재 계정이 접속 가능한 모든 테이블 조회

SELECT *
FROM DBA_TABLES;        -- 관리권한의 사용자만 접근 가능

/* 시퀀스 */
CREATE TABLE DEPT_SEQ AS SELECT * FROM DEPT d WHERE 1 != 1;
SELECT *
FROM DEPT_SEQ;

DROP TABLE DEPT_SEQ;

CREATE SEQUENCE SEQ_DEPT_SEQUENCE
INCREMENT BY 10     -- 증가하는 값
START WITH 10       -- 시작 값
MAXVALUE 90         -- 최댓 값
MINVALUE 0          -- 최솟 값
NOCYCLE             -- 최대값이면 정지, 순환금지
CACHE 2;

SELECT *
FROM USER_SEQUENCES;

-- 시퀀스이을? NEXTVAL
INSERT INTO DEPT_SEQ (DEPTNO, DNAME, LOC)
VALUES (SEQ_DEPT_SEQUENCE.NEXTVAL, 'DATABASE', 'BUSAN');

INSERT INTO DEPT_SEQ (DEPTNO, DNAME, LOC)
VALUES (SEQ_DEPT_SEQUENCE.NEXTVAL, 'DATABASE1', 'SEOUL');

SELECT *
FROM DEPT_SEQ ORDER BY DEPTNO;

SELECT SEQ_DEPT_SEQUENCE.CURRVAL        -- [시퀀스.CURRVAL] 가장 마지막의 시퀀스 확인
FROM DUAL;

-- 시퀀스 수정
ALTER SEQUENCE SEQ_DEPT_SEQUENCE INCREMENT BY 3 MAXVALUE 99 CYCLE;
SELECT *
FROM USER_SEQUENCES;

DROP SEQUENCE SEQ_DEPT_SEQUENCE;

