/* DDL */
-- 테이블 생성
CREATE TABLE EMP_DDL(
    EMPNO NUMBER(4),
    ENAME VARCHAR2(10),
    JOB VARCHAR2(9),
    MGR NUMBER(4),
    HIREDATE DATE,
    SAL NUMBER(7,2),
    COMM NUMBER(7,2),
    DEPTNO NUMBER(2)
);
SELECT *
FROM EMP_DDL;

CREATE TABLE EMP_DDL1 AS
SELECT *
FROM EMP
WHERE DEPTNO = 30;

CREATE TABLE EMP_DDL2 AS
SELECT *
FROM EMP
WHERE 1 != 1;

SELECT *
FROM EMP_DDL2;

-- 테이블 수정
ALTER TABLE EMP_DDL1
    ADD HP VARCHAR2(20);

SELECT *
FROM EMP_DDL1;      -- 테이블 조회

ALTER TABLE EMP_DDL1 RENAME COLUMN HP TO TEL;       -- HP 컬럼이름 수정
COMMIT;
ALTER TABLE EMP_DDL1 MODIFY  EMPNO NUMBER(10);      -- 자료형 변경
ALTER TABLE EMP_DDL1 DROP COLUMN TEL;       -- 컬럼 삭제
TRUNCATE TABLE EMP_DDL1;        -- 전체 데이터 삭제
DROP TABLE EMP_DDL1;
DROP TABLE EMP_DDL2;
DROP TABLE EMP_DDL;
----------------------------------------------------------------------------
/* 제약조건*/
CREATE TABLE TBL_EX (
    LOGIN_ID VARCHAR2(20) NOT NULL ,
    LOGIN_PW VARCHAR2(20) NOT NULL ,
    TEL VARCHAR2(20)
);
SELECT *
FROM TBL_EX;

INSERT INTO TBL_EX te (LOGIN_ID, LOGIN_PW, TEL)
VALUES ('AAAA', '1234', NULL);

INSERT INTO TBL_EX te (LOGIN_ID, LOGIN_PW, TEL)
VALUES ('BBBB', 'NULL', NULL);
-- ALTER TABLE TBL_EX MODIFY TEL NOT NULL;  -- 기존 데이터가 변경할 제약조건에 부합되면 적용이 안됨
UPDATE TBL_EX SET TEL = '010-8718-8656' WHERE LOGIN_ID = 'AAAA';        -- 정보 변경

-- UNIQUE
CREATE TABLE TBL_UNIQ (
    LOGIN_ID varchar(20) PRIMARY KEY ,       -- 중복과 null을 허용하지 않는다.
    LOGIN_PW varchar(20) NOT NULL ,
    TEL varchar(20)
);
SELECT OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME FROM USER_CONSTRAINTS;