/* DDL */
-- 테이블 생성
CREATE TABLE EMP_DDL(
    EMPNO NUMBER(4),
    ENAME VARCHAR2(10),
    JOB VARCHAR2(9),
    MGR NUMBER(4),
    HIREDATE DATE,
    SAL NUMBER(7,2),
    COMM NUMBER(7,2),
    DEPTNO NUMBER(2)
);
SELECT *
FROM EMP_DDL;

CREATE TABLE EMP_DDL1 AS
SELECT *
FROM EMP
WHERE DEPTNO = 30;

CREATE TABLE EMP_DDL2 AS
SELECT *
FROM EMP
WHERE 1 != 1;

SELECT *
FROM EMP_DDL2;

-- 테이블 수정
ALTER TABLE EMP_DDL1
    ADD HP VARCHAR2(20);

SELECT *
FROM EMP_DDL1;      -- 테이블 조회

ALTER TABLE EMP_DDL1 RENAME COLUMN HP TO TEL;       -- HP 컬럼이름 수정
COMMIT;
ALTER TABLE EMP_DDL1 MODIFY  EMPNO NUMBER(10);      -- 자료형 변경
ALTER TABLE EMP_DDL1 DROP COLUMN TEL;       -- 컬럼 삭제
TRUNCATE TABLE EMP_DDL1;        -- 전체 데이터 삭제
DROP TABLE EMP_DDL1;
DROP TABLE EMP_DDL2;
DROP TABLE EMP_DDL;
----------------------------------------------------------------------------
/* 제약조건*/
CREATE TABLE TBL_EX (
    LOGIN_ID VARCHAR2(20) NOT NULL ,
    LOGIN_PW VARCHAR2(20) NOT NULL ,
    TEL VARCHAR2(20)
);
SELECT *
FROM TBL_EX;

INSERT INTO TBL_EX te (LOGIN_ID, LOGIN_PW, TEL)
VALUES ('AAAA', '1234', NULL);

INSERT INTO TBL_EX te (LOGIN_ID, LOGIN_PW, TEL)
VALUES ('BBBB', 'NULL', NULL);
-- ALTER TABLE TBL_EX MODIFY TEL NOT NULL;  -- 기존 데이터가 변경할 제약조건에 부합되면 적용이 안됨
UPDATE TBL_EX SET TEL = '010-8718-8656' WHERE LOGIN_ID = 'AAAA';        -- 정보 변경

-- UNIQUE
CREATE TABLE TBL_UNIQ (
    LOGIN_ID varchar(20) PRIMARY KEY ,       -- 중복과 null을 허용하지 않는다.
    LOGIN_PW varchar(20) NOT NULL ,
    TEL varchar(20)
);
SELECT OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME FROM USER_CONSTRAINTS;

SELECT OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME, R_OWNER, R_CONSTRAINT_NAME
FROM  USER_CONSTRAINTS
WHERE TABLE_NAME IN ('EMP', 'DEPT');

/* CHECK */
--  010-145-5555
-- 010 - [1-5] [0-9][0-9] [0-9]- [0-9][0-9][0-9][0-9]
-- 010-\d\d\d\d -\d\d\d\d
-- 010 - \d{4} - \d{4}
CREATE TABLE TBL_CHK (
    LOGIN_ID VARCHAR2(20) CONSTRAINT TBLCK_LOGINIG_PK PRIMARY KEY ,
    LOGIN_PW VARCHAR2(20) CONSTRAINT TBLCK_LOGINPW_CK CHECK (LENGTH(LOGIN_PW) > 3),
    TEL VARCHAR(20)
);

-- 1. EMP 테이블에서 사원번호가 7521인 사원의 직업과 같고, 사원번호 7934인 사원의 급여보다 많은 사원은 사번, 이름, 직업, 급여 출력
SELECT EMPNO, ENAME, JOB, SAL
FROM EMP WHERE JOB = (SELECT JOB FROM EMP WHERE EMPNO = 7521)
AND SAL > (SELECT SAL FROM EMP WHERE EMPNO = 7934);

-- 2. 직업별로 최소급여를 받는 사원의 정보를 사원번호, 이름, 업무, 부서명으로 출력( 직업별 내림차순)
SELECT E.EMPNO, E.ENAME, E.JOB, D.DNAME, E.SAL
FROM EMP E JOIN DEPT D ON E.DEPTNO = D.DEPTNO
WHERE E.SAL IN (SELECT MIN(SAL) FROM EMP GROUP BY JOB)
ORDER BY E.JOB DESC;

-- 3. 각 사원별 커머션이 0 또는 NULL이고 부서 위치가 'GO'로 끝나는 사원의 정보를 사원번호, 사원이름, 커머션, 부서번호, 부서명, 
-- 부서위치를 출력(보너스가 NULL 이면 0으로 출력)
SELECT
    EMPNO,
    ENAME,
    NVL(COMM, 0) , -- 보너스가 NULL인 경우 0으로 출력
    EMP.DEPTNO,
    D.DNAME,
    D.LOC
FROM EMP JOIN DEPT D ON EMP.DEPTNO = D.DEPTNO
WHERE
    (COMM = 0 OR COMM IS NULL) -- 커미션이 0 또는 NULL인 경우
  AND D.LOC LIKE '%GO'; -- 부서 위치가 'GO'로 끝나는 경우